### ISSUE TITLE
NameError (uninitialized constant Resolvers::ProducerSearch::SearchObject)

### ISSUE THREAD

**Issue by jotolo** [RStankov/SearchObjectGraphQL#2]
I'm doing the gem installation like documentation says and I'm receiving this error:
```NameError (uninitialized constant Resolvers::ProducerSearch::SearchObject)```
My producer_search class:
```
module Resolvers
  class ProducerSearch
    include SearchObject.module(:graphql)    

    type types[ProducerType]
    scope { Producer.all }

    option(:name, type: types.String) { |scope, value| scope.where(name: value) }
  end
end
```
And the complete log:
```
NameError (uninitialized constant Resolvers::ProducerSearch::SearchObject):
  
app/graphql/resolvers/producer_search.rb:5:in `<class:ProducerSearch>'
app/graphql/resolvers/producer_search.rb:3:in `<module:Resolvers>'
app/graphql/resolvers/producer_search.rb:2:in `<top (required)>'
app/graphql/types/query_type.rb:282:in `block in <top (required)>'
app/graphql/invent_schema.rb:87:in `<top (required)>'
app/controllers/graphql_controller.rb:37:in `execute_query'
app/controllers/graphql_controller.rb:11:in `execute'
Started POST "/graphql" for 127.0.0.1 at 2017-12-18 10:16:05 -0500
Processing by GraphqlController#execute as */*
  Parameters: {"query"=>"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n", "graphql"=>{"query"=>"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"}}
Schema#resolve_type(type, obj, ctx) with 2 arguments is deprecated, it now accepts 3 arguments, see:
/home/jotolo/Documents/Work/Inventory/invent/app/graphql/invent_schema.rb:25:in `block in <top (required)>'
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)


  
LoadError (Unable to autoload constant Types::MutationType, expected /home/jotolo/Documents/Work/Inventory/invent/app/graphql/types/mutation_type.rb to define it):
  
app/graphql/invent_schema.rb:77:in `block in <top (required)>'
app/graphql/invent_schema.rb:1:in `<top (required)>'
app/controllers/graphql_controller.rb:37:in `execute_query'
app/controllers/graphql_controller.rb:11:in `execute'


```
Any ideas?

**Comment by RStankov** [comment]
Hi, does adding the following to the top of the file helps?

```ruby
require 'search_object'
require 'search_object_graphql'
```

**Comment by jotolo** [comment]
Not working.
```
LoadError (cannot load such file -- search_object_graphql):
  
app/graphql/resolvers/producer_search.rb:2:in `<top (required)>'
app/graphql/types/query_type.rb:282:in `block in <top (required)>'
app/graphql/invent_schema.rb:1:in `<top (required)>'
app/controllers/graphql_controller.rb:37:in `execute_query'
app/controllers/graphql_controller.rb:11:in `execute'
Started POST "/graphql" for 127.0.0.1 at 2017-12-18 10:40:07 -0500
Processing by GraphqlController#execute as */*
  Parameters: {"query"=>"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n", "graphql"=>{"query"=>"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"}}
Schema#resolve_type(type, obj, ctx) with 2 arguments is deprecated, it now accepts 3 arguments, see:
/home/jotolo/Documents/Work/Inventory/invent/app/graphql/invent_schema.rb:25:in `block in <top (required)>'
Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.0ms)


  
LoadError (Unable to autoload constant Types::MutationType, expected /home/jotolo/Documents/Work/Inventory/invent/app/graphql/types/mutation_type.rb to define it):
  
app/graphql/invent_schema.rb:77:in `block in <top (required)>'

```

**Comment by jotolo** [comment]
Hi again, this is my Gemfile, in case you want to reproduce. And it's a rails API app.
```
source 'https://rubygems.org'
#source 'http://packages.matcom.uh.cu:8081/repository/rubygems-proxy/'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
gem 'bcrypt', platforms: :ruby

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'shoulda-matchers'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'graphql'
gem 'graphiql-rails', group: :development
gem 'graphql-errors'
gem 'graphql-batch'
gem 'graphql-guard'
gem 'search_object_graphql'
#gem 'search_object'
#gem 'graphql-formatter'

gem 'devise_token_auth'
gem 'omniauth'
gem 'chemistry_rails', :git => 'git://github.com/jotolo/chemistry_rails.git', :branch => 'radionuclides'
gem 'countries', :require => 'countries/global'
gem 'factory_bot_rails'
gem 'faker'

# Auditable System
gem 'audited'

#for windows os
gem 'wdm', '>= 0.1.0' if Gem.win_platform?
```

**Comment by jotolo** [comment]
Solved! you just need to add this at the top of the file:
```
require 'search_object'
require 'search_object/plugin/graphql'
```
Thanks @RStankov for the hint! ;)

**Comment by RStankov** [comment]
No worries, glad that you we able to solve the issue 🙌
